import { Button } from "@/shared/ui/Button/Button";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeSwitcher } from "@/widget/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-background text-text`}>
        <ThemeSwitcher />
        {children}
      </body>
    </html>
  );
}
