import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import localFont from "next/font/local";

import { Navbar } from "@/widget/Navbar";
import "../globals.css";
import { Burger } from "@/widget/Burger/ui/Burger";

const font = localFont({
  src: "../fonts/SourceCodePro-VariableFont_wght.ttf",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "de" }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang='en' className='scroll-smooth'>
      <body
        className={`${font.className} relative min-w-full min-h-screen bg-linear-bg bg-no-repeat dark:bg-dark-linear-bg dark:bg-dark-background text-text dark:text-dark-text transition-all`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar className='bg-navbar dark:bg-dark-navbar' />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
